k1 = Kitten.create!(name: "Garfield", age: 3, cuteness: 2, softness: 3)
k2 = Kitten.create!(name: "Cinnamon", age: 1.5, cuteness: 1, softness: 2)
k3 = Kitten.create!(name: "Apollo", age: 2, cuteness: 4, softness: 5)
k4 = Kitten.create!(name: "Loki", age: 2, cuteness: 3, softness: 1)
k5 = Kitten.create!(name: "Simba", age: 2.5, cuteness: 3, softness: 1)
k6 = Kitten.create!(name: "Jack", age: 1, cuteness: 5, softness: 3)
k7 = Kitten.create!(name: "Max", age: 0.5, cuteness: 2, softness: 2)